/*

gpp -I ../include test-fixed_vector2.cpp && d ./a.out

clear ; ./a.out -a

*/

// Generated by ChatGPT 5.2 Thinking

// SPDX-FileCopyrightText: Steven Ward
// SPDX-License-Identifier: MPL-2.0

#include "fixed_vector.hpp"

#include <fmt/ranges.h>

#include <cassert>
#include <cstddef>
#include <initializer_list>
#include <span>
#include <stdexcept>
#include <utility>
#include <vector>

/*
template <class T>
void print_span(const std::string_view label,
        const std::span<const T> sp)
{
    fmt::println("{}: {}", label, sp);
}
*/

inline
void section(const std::string_view title)
{
    fmt::println("\n=== {} ===", title);
}

template <class Fn>
void expect_throws(const std::string_view label, Fn&& fn)
{
    try {
        std::forward<Fn>(fn)();
        fmt::println("FAIL (no exception): {}", label);
    } catch (const std::exception& e) {
        fmt::println("OK (threw {}): {} -> {}", typeid(e).name(), label, e.what());
    } catch (...) {
        fmt::println("OK (threw unknown): {}", label);
    }
}


int main()
{
    using T = int;
    constexpr std::size_t N = 8;

    section("Constructors");

    // fixed_vector(const std::size_t count)
    fixed_vector<T, N> a_count(3);
    fmt::println("a_count.span(): {}", a_count.span());

    // fixed_vector(const std::size_t count, const T& value)
    fixed_vector<T, N> a_count_value(4, 7);
    fmt::println("a_count_value.span(): {}", a_count_value.span());

    // fixed_vector(const std::span<const T> spn)
    T raw1[] = {1, 2, 3, 4};
    std::span<const T> sp1(raw1);
    fixed_vector<T, N> a_span(sp1);
    fmt::println("a_span.span(): {}", a_span.span());

    // fixed_vector(It first, S last)
    std::vector<T> v1 = {10, 20, 30, 40, 50};
    fixed_vector<T, N> a_it_last(v1.begin(), v1.end());
    fmt::println("a_it_last.span(): {}", a_it_last.span());

    // fixed_vector(It first, const std::size_t count)
    fixed_vector<T, N> a_it_count(v1.begin() + 1, 3);
    fmt::println("a_it_count.span(): {}", a_it_count.span());

    // fixed_vector(const std::initializer_list<T> il)
    fixed_vector<T, N> a_il = fixed_vector<T, N>({9, 8, 7});
    fmt::println("a_il.span(): {}", a_il.span());

    // fixed_vector(std::from_range_t, R&& rg)
    auto rg = std::views::iota(1, 6); // 1..5
    fixed_vector<T, N> a_from_range(std::from_range, rg);
    fmt::println("a_from_range.span(): {}", a_from_range.span());

    section("operator=(std::initializer_list)");

    fixed_vector<T, N> b0(2, 1);
    fmt::println("b0 initial: {}", b0.span());
    b0 = {42, 43, 44};
    fmt::println("b0 after: {}", b0.span());

    section("pop_back");

    fixed_vector<T, N> b1({1, 2, 3});
    fmt::println("b1 before pop_back: {}", b1.span());
    b1.pop_back();
    fmt::println("b1 after pop_back: {}", b1.span());
    b1.pop_back();
    b1.pop_back();
    b1.pop_back(); // pop empty should do nothing
    fmt::println("b1 after popping to empty: {}", b1.span());

    section("emplace_back / push_back");

    fixed_vector<T, N> b2(0);
    b2.emplace_back(100);
    b2.push_back(200);
    T x = 300;
    b2.push_back(x);                // const T&
    b2.push_back(T{400});           // T&&
    fmt::println("b2 after appends: {}", b2.span());

    section("fill_capacity / fill_size");

    fixed_vector<T, N> b3({1, 2, 3});
    b3.fill_size(9);
    fmt::println("b3 after fill_size(9): {}", b3.span());

    fixed_vector<T, N> b4({1, 2, 3});
    b4.fill_capacity(5);
    fmt::println("b4 after fill_capacity(5): {}", b4.span());
    fmt::println("b4.size() = {}", b4.size());

    section("append_range overloads");

    fixed_vector<T, N> c0({1, 2});

    // append_range(span)
    T raw2[] = {3, 4, 5};
    c0.append_range(std::span<const T>(raw2));
    fmt::println("c0 after append span: {}", c0.span());

    // append_range(It first, S last)
    std::vector<T> v2 = {6, 7, 8};
    c0.append_range(v2.begin(), v2.end());
    fmt::println("c0 after append iter/sentinel: {}", c0.span());

    // append_range(It first, count)
    std::vector<T> v3 = {9, 10, 11, 12};
    fixed_vector<T, N> c1({1});
    c1.append_range(v3.begin() + 1, 2); // 10,11
    fmt::println("c1 after append iter/count: {}", c1.span());

    // append_range(initializer_list)
    fixed_vector<T, N> c2({1});
    c2.append_range({2, 3, 4});
    fmt::println("c2 after append init_list: {}", c2.span());

    // append_range(R&& rg)
    fixed_vector<T, N> c3({1});
    c3.append_range(std::views::iota(20, 24)); // 20..23
    fmt::println("c3 after append range: {}", c3.span());

    section("assign_range overloads");

    fixed_vector<T, N> d0({1, 2, 3, 4});

    // assign_range(span)
    T raw3[] = {9, 9};
    d0.assign_range(std::span<const T>(raw3));
    fmt::println("d0 after assign span: {}", d0.span());

    // assign_range(It first, S last)
    std::vector<T> v4 = {5, 6, 7};
    d0.assign_range(v4.begin(), v4.end());
    fmt::println("d0 after assign iter/sentinel: {}", d0.span());

    // assign_range(It first, count)
    std::vector<T> v5 = {100, 101, 102, 103};
    d0.assign_range(v5.begin() + 1, 2); // 101,102
    fmt::println("d0 after assign iter/count: {}", d0.span());

    // assign_range(initializer_list)
    d0.assign_range({8, 8, 8});
    fmt::println("d0 after assign init_list: {}", d0.span());

    // assign_range(R&& rg)
    d0.assign_range(std::views::iota(1, 4)); // 1..3
    fmt::println("d0 after assign range: {}", d0.span());

    section("span() and operator[] and at()");

    fixed_vector<T, N> e0({11, 22, 33});
    fmt::println("e0.span(): {}", e0.span());

    // operator[] (capacity-based per your design)
    fmt::println("e0[0] = {}", e0[0]);
    fmt::println("e0[1] = {}", e0[1]);

    // at() (size-checked)
    fmt::println("e0.at(2) = {}", e0.at(2));
    expect_throws("e0.at(3) throws out_of_range", [&] { (void)e0.at(3); });

    // demonstrate that operator[] can access beyond size (intentional)
    // (This reads an element that exists in underlying array storage, but is not in span()).
    fmt::println("e0[7] (beyond size, within capacity) = {}", e0[7]);

    section("Overflow behavior (std::bad_alloc)");

    expect_throws("construct count > capacity", [&] {
        fixed_vector<T, N> z(N + 1);
        (void)z;
    });

    expect_throws("emplace_back overflow", [&] {
        fixed_vector<T, N> z;
        z.fill_capacity(1);
        z.emplace_back(2);
    });

    expect_throws("append_range(span) overflow", [&] {
        fixed_vector<T, N> z({1, 2, 3, 4, 5, 6, 7});
        T more[] = {8, 9};
        z.append_range(std::span<const T>(more));
    });

    expect_throws("append_range(range sized) overflow", [&] {
        fixed_vector<T, N> z({1, 2, 3, 4, 5, 6, 7});
        z.append_range(std::views::iota(0, 10)); // sized, too many
    });

    return 0;
}

/*

Output:

=== Constructors ===
a_count.span(): [0, 0, 0]
a_count_value.span(): [7, 7, 7, 7]
a_span.span(): [1, 2, 3, 4]
a_it_last.span(): [10, 20, 30, 40, 50]
a_it_count.span(): [20, 30, 40]
a_il.span(): [9, 8, 7]
a_from_range.span(): [1, 2, 3, 4, 5]

=== operator=(std::initializer_list) ===
b0 initial: [1, 1]
b0 after: [42, 43, 44]

=== pop_back ===
b1 before pop_back: [1, 2, 3]
b1 after pop_back: [1, 2]
b1 after popping to empty: []

=== emplace_back / push_back ===
b2 after appends: [100, 200, 300, 400]

=== fill_capacity / fill_size ===
b3 after fill_size(9): [9, 9, 9]
b4 after fill_capacity(5): [5, 5, 5, 5, 5, 5, 5, 5]
b4.size() = 8

=== append_range overloads ===
c0 after append span: [1, 2, 3, 4, 5]
c0 after append iter/sentinel: [1, 2, 3, 4, 5, 6, 7, 8]
c1 after append iter/count: [1, 10, 11]
c2 after append init_list: [1, 2, 3, 4]
c3 after append range: [1, 20, 21, 22, 23]

=== assign_range overloads ===
d0 after assign span: [9, 9]
d0 after assign iter/sentinel: [5, 6, 7]
d0 after assign iter/count: [101, 102]
d0 after assign init_list: [8, 8, 8]
d0 after assign range: [1, 2, 3]

=== span() and operator[] and at() ===
e0.span(): [11, 22, 33]
e0[0] = 11
e0[1] = 22
e0.at(2) = 33
OK (threw St12out_of_range): e0.at(3) throws out_of_range -> fixed_vector: index >= size
e0[7] (beyond size, within capacity) = 0

=== Overflow behavior (std::bad_alloc) ===
OK (threw St9bad_alloc): construct count > capacity -> std::bad_alloc
OK (threw St9bad_alloc): emplace_back overflow -> std::bad_alloc
OK (threw St9bad_alloc): append_range(span) overflow -> std::bad_alloc
OK (threw St9bad_alloc): append_range(range sized) overflow -> std::bad_alloc

*/
