/*

gpp -I ../include test-fixed_vector3.cpp && d ./a.out

clear ; ./a.out -a

*/

// Generated by Claude Sonnet 4.5 Extended

// SPDX-FileCopyrightText: Steven Ward
// SPDX-License-Identifier: MPL-2.0

#include "fixed_vector.hpp"

#include <fmt/ranges.h>

#include <algorithm>
#include <cassert>
#include <numeric>
#include <stdexcept>
#include <vector>

void test_default_constructor()
{
    fmt::println("=== Testing Default Constructor ===");
    {
        fixed_vector<int, 10> v;
        assert(v.size() == 0);
        assert(v.is_empty());
        assert(!v.is_full());
        assert(v.remaining_space() == 10);
        fmt::println("Default constructor: {}", v.span());
    }
    fmt::println("");
}

void test_count_constructor()
{
    fmt::println("=== Testing Count Constructor ===");
    {
        // Success case
        fixed_vector<int, 10> v(5);
        assert(v.size() == 5);
        assert(!v.is_empty());
        assert(!v.is_full());
        fmt::println("Count constructor (5): {}", v.span());
    }
    {
        // Failure case - exceeds capacity
        try {
            fixed_vector<int, 10> v(20);
            assert(false && "Should have thrown");
        } catch (const std::bad_alloc&) {
            fmt::println("Count constructor correctly threw for count > capacity");
        }
    }
    fmt::println("");
}

void test_count_value_constructor()
{
    fmt::println("=== Testing Count+Value Constructor ===");
    {
        // Success case
        fixed_vector<int, 10> v(5, 42);
        assert(v.size() == 5);
        assert(std::all_of(v.begin(), v.end(), [](int x) { return x == 42; }));
        fmt::println("Count+value constructor (5, 42): {}", v.span());
    }
    {
        // Failure case - exceeds capacity
        try {
            fixed_vector<int, 10> v(20, 42);
            assert(false && "Should have thrown");
        } catch (const std::bad_alloc&) {
            fmt::println("Count+value constructor correctly threw for count > capacity");
        }
    }
    fmt::println("");
}

void test_span_constructor()
{
    fmt::println("=== Testing Span Constructor ===");
    {
        // Success case
        std::array<int, 5> arr = {1, 2, 3, 4, 5};
        fixed_vector<int, 10> v((std::span<const int>(arr)));
        assert(v.size() == 5);
        fmt::println("Span constructor: {}", v.span());
    }
    {
        // Failure case - span too large
        std::array<int, 15> arr{};
        try {
            fixed_vector<int, 10> v((std::span<const int>(arr)));
            assert(false && "Should have thrown");
        } catch (const std::bad_alloc&) {
            fmt::println("Span constructor correctly threw for span > capacity");
        }
    }
    fmt::println("");
}

void test_iterator_constructor()
{
    fmt::println("=== Testing Iterator Constructor ===");
    {
        // Success case
        std::vector<int> src = {10, 20, 30, 40};
        fixed_vector<int, 10> v(src.begin(), src.end());
        assert(v.size() == 4);
        fmt::println("Iterator constructor: {}", v.span());
    }
    {
        // Failure case - too many elements
        std::vector<int> src(20, 1);
        try {
            fixed_vector<int, 10> v(src.begin(), src.end());
            assert(false && "Should have thrown");
        } catch (const std::bad_alloc&) {
            fmt::println("Iterator constructor correctly threw for range > capacity");
        }
    }
    fmt::println("");
}

void test_iterator_count_constructor()
{
    fmt::println("=== Testing Iterator+Count Constructor ===");
    {
        // Success case
        std::vector<int> src = {1, 2, 3, 4, 5, 6, 7, 8};
        fixed_vector<int, 10> v(src.begin(), 5);
        assert(v.size() == 5);
        fmt::println("Iterator+count constructor: {}", v.span());
    }
    {
        // Failure case - count too large
        std::vector<int> src(20, 1);
        try {
            fixed_vector<int, 10> v(src.begin(), 15);
            assert(false && "Should have thrown");
        } catch (const std::bad_alloc&) {
            fmt::println("Iterator+count constructor correctly threw for count > capacity");
        }
    }
    fmt::println("");
}

void test_initializer_list_constructor()
{
    fmt::println("=== Testing Initializer List Constructor ===");
    {
        // Success case
        fixed_vector<int, 10> v({1, 2, 3, 4, 5});
        assert(v.size() == 5);
        fmt::println("Initializer list constructor: {}", v.span());
    }
    {
        // Failure case - too many elements
        try {
            fixed_vector<int, 5> v({1, 2, 3, 4, 5, 6, 7, 8});
            assert(false && "Should have thrown");
        } catch (const std::bad_alloc&) {
            fmt::println("Initializer list constructor correctly threw for list > capacity");
        }
    }
    fmt::println("");
}

void test_range_constructor()
{
    fmt::println("=== Testing Range Constructor ===");
    {
        // Success case
        std::vector<int> src = {100, 200, 300};
        fixed_vector<int, 10> v(std::from_range, src);
        assert(v.size() == 3);
        fmt::println("Range constructor: {}", v.span());
    }
    {
        // Failure case - range too large
        std::vector<int> src(20, 1);
        try {
            fixed_vector<int, 10> v(std::from_range, src);
            assert(false && "Should have thrown");
        } catch (const std::bad_alloc&) {
            fmt::println("Range constructor correctly threw for range > capacity");
        }
    }
    fmt::println("");
}

void test_copy_constructor()
{
    fmt::println("=== Testing Copy Constructor ===");
    {
        fixed_vector<int, 10> v1({1, 2, 3, 4, 5});
        fixed_vector<int, 10> v2(v1);
        assert(v2.size() == 5);
        assert(v1 == v2);
        fmt::println("Original: {}", v1.span());
        fmt::println("Copy: {}", v2.span());
    }
    fmt::println("");
}

void test_move_constructor()
{
    fmt::println("=== Testing Move Constructor ===");
    {
        fixed_vector<int, 10> v1({1, 2, 3, 4, 5});
        fixed_vector<int, 10> v2(std::move(v1));
        assert(v2.size() == 5);
        fmt::println("Moved-to: {}", v2.span());
    }
    fmt::println("");
}

void test_copy_assignment()
{
    fmt::println("=== Testing Copy Assignment ===");
    {
        fixed_vector<int, 10> v1({1, 2, 3});
        fixed_vector<int, 10> v2;
        v2 = v1;
        assert(v2.size() == 3);
        assert(v1 == v2);
        fmt::println("After copy assignment: {}", v2.span());
    }
    fmt::println("");
}

void test_move_assignment()
{
    fmt::println("=== Testing Move Assignment ===");
    {
        fixed_vector<int, 10> v1({1, 2, 3});
        fixed_vector<int, 10> v2;
        v2 = std::move(v1);
        assert(v2.size() == 3);
        fmt::println("After move assignment: {}", v2.span());
    }
    fmt::println("");
}

void test_initializer_list_assignment()
{
    fmt::println("=== Testing Initializer List Assignment ===");
    {
        fixed_vector<int, 10> v;
        v = {10, 20, 30, 40};
        assert(v.size() == 4);
        fmt::println("After initializer list assignment: {}", v.span());
    }
    fmt::println("");
}

void test_size_queries()
{
    fmt::println("=== Testing Size Queries ===");
    {
        fixed_vector<int, 10> v({1, 2, 3});
        assert(v.max_size() == 10);
        assert(v.capacity() == 10);
        assert(v.size() == 3);
        assert(v.remaining_space() == 7);
        assert(!v.is_empty());
        assert(!v.is_full());
        fmt::println("max_size: {}", v.max_size());
        fmt::println("capacity: {}", v.capacity());
        fmt::println("size: {}", v.size());
        fmt::println("remaining_space: {}", v.remaining_space());
        fmt::println("is_empty: {}", v.is_empty());
        fmt::println("is_full: {}", v.is_full());
    }
    {
        fixed_vector<int, 5> v({1, 2, 3, 4, 5});
        assert(v.is_full());
        assert(!v.is_empty());
        fmt::println("Full vector is_full: {}", v.is_full());
    }
    fmt::println("");
}

void test_clear()
{
    fmt::println("=== Testing clear() ===");
    {
        fixed_vector<int, 10> v({1, 2, 3, 4, 5});
        fmt::println("Before clear: {}", v.span());
        v.clear();
        assert(v.size() == 0);
        assert(v.is_empty());
        fmt::println("After clear: {}", v.span());
    }
    fmt::println("");
}

void test_resize()
{
    fmt::println("=== Testing resize() ===");
    {
        // Resize up with default values
        fixed_vector<int, 10> v({1, 2, 3});
        fmt::println("Before resize(5): {}", v.span());
        v.resize(5);
        assert(v.size() == 5);
        fmt::println("After resize(5): {}", v.span());
    }
    {
        // Resize down
        fixed_vector<int, 10> v({1, 2, 3, 4, 5});
        fmt::println("Before resize(3): {}", v.span());
        v.resize(3);
        assert(v.size() == 3);
        fmt::println("After resize(3): {}", v.span());
    }
    {
        // Resize with value
        fixed_vector<int, 10> v({1, 2});
        fmt::println("Before resize(5, 99): {}", v.span());
        v.resize(5, 99);
        assert(v.size() == 5);
        fmt::println("After resize(5, 99): {}", v.span());
    }
    {
        // Failure case - resize beyond capacity
        fixed_vector<int, 10> v;
        try {
            v.resize(20);
            assert(false && "Should have thrown");
        } catch (const std::bad_alloc&) {
            fmt::println("resize() correctly threw for count > capacity");
        }
    }
    fmt::println("");
}

void test_pop_back()
{
    fmt::println("=== Testing pop_back() ===");
    {
        fixed_vector<int, 10> v({1, 2, 3, 4, 5});
        fmt::println("Before pop_back: {}", v.span());
        v.pop_back();
        assert(v.size() == 4);
        fmt::println("After pop_back: {}", v.span());
    }
    {
        // Pop from empty (should be safe)
        fixed_vector<int, 10> v;
        v.pop_back();
        assert(v.size() == 0);
        fmt::println("pop_back on empty vector is safe");
    }
    fmt::println("");
}

void test_emplace_back()
{
    fmt::println("=== Testing emplace_back() ===");
    {
        fixed_vector<int, 10> v;
        v.emplace_back(10);
        v.emplace_back(20);
        v.emplace_back(30);
        assert(v.size() == 3);
        fmt::println("After emplace_back: {}", v.span());
    }
    {
        // Failure case - emplace on full
        fixed_vector<int, 3> v({1, 2, 3});
        try {
            v.emplace_back(4);
            assert(false && "Should have thrown");
        } catch (const std::bad_alloc&) {
            fmt::println("emplace_back() correctly threw when full");
        }
    }
    fmt::println("");
}

void test_try_emplace_back()
{
    fmt::println("=== Testing try_emplace_back() ===");
    {
        fixed_vector<int, 10> v;
        bool success = v.try_emplace_back(100);
        assert(success);
        assert(v.size() == 1);
        fmt::println("try_emplace_back success: {}", v.span());
    }
    {
        // Failure case - try emplace on full
        fixed_vector<int, 3> v({1, 2, 3});
        bool success = v.try_emplace_back(4);
        assert(!success);
        assert(v.size() == 3);
        fmt::println("try_emplace_back correctly returned false when full");
    }
    fmt::println("");
}

void test_push_back()
{
    fmt::println("=== Testing push_back() ===");
    {
        fixed_vector<int, 10> v;
        v.push_back(5);
        v.push_back(10);
        int val = 15;
        v.push_back(val);
        assert(v.size() == 3);
        fmt::println("After push_back: {}", v.span());
    }
    {
        // Failure case - push on full
        fixed_vector<int, 3> v({1, 2, 3});
        try {
            v.push_back(4);
            assert(false && "Should have thrown");
        } catch (const std::bad_alloc&) {
            fmt::println("push_back() correctly threw when full");
        }
    }
    fmt::println("");
}

void test_try_push_back()
{
    fmt::println("=== Testing try_push_back() ===");
    {
        fixed_vector<int, 10> v;
        bool success1 = v.try_push_back(5);
        bool success2 = v.try_push_back(10);
        assert(success1 && success2);
        assert(v.size() == 2);
        fmt::println("try_push_back success: {}", v.span());
    }
    {
        // Failure case
        fixed_vector<int, 3> v({1, 2, 3});
        bool success = v.try_push_back(4);
        assert(!success);
        fmt::println("try_push_back correctly returned false when full");
    }
    fmt::println("");
}

void test_unchecked_operations()
{
    fmt::println("=== Testing unchecked operations ===");
    {
        fixed_vector<int, 10> v;
        v.unchecked_emplace_back(1);
        v.unchecked_emplace_back(2);
        v.unchecked_push_back(3);
        v.unchecked_push_back(4);
        assert(v.size() == 4);
        fmt::println("After unchecked operations: {}", v.span());
    }
    fmt::println("");
}

void test_fill_capacity()
{
    fmt::println("=== Testing fill_capacity() ===");
    {
        fixed_vector<int, 10> v;
        v.fill_capacity(7);
        assert(v.size() == 10);
        assert(v.is_full());
        assert(std::all_of(v.begin(), v.end(), [](int x) { return x == 7; }));
        fmt::println("After fill_capacity(7): {}", v.span());
    }
    fmt::println("");
}

void test_fill_size()
{
    fmt::println("=== Testing fill_size() ===");
    {
        fixed_vector<int, 10> v({1, 2, 3, 4, 5});
        v.fill_size(99);
        assert(v.size() == 5);
        assert(std::all_of(v.begin(), v.end(), [](int x) { return x == 99; }));
        fmt::println("After fill_size(99): {}", v.span());
    }
    fmt::println("");
}

void test_append_range()
{
    fmt::println("=== Testing append_range() ===");
    {
        // Append from span
        fixed_vector<int, 10> v({1, 2, 3});
        std::array<int, 3> arr = {4, 5, 6};
        v.append_range(std::span<const int>(arr));
        assert(v.size() == 6);
        fmt::println("After append_range(span): {}", v.span());
    }
    {
        // Append from iterators
        fixed_vector<int, 10> v({1, 2});
        std::vector<int> src = {3, 4, 5};
        v.append_range(src.begin(), src.end());
        assert(v.size() == 5);
        fmt::println("After append_range(iterators): {}", v.span());
    }
    {
        // Append from iterator + count
        fixed_vector<int, 10> v({1, 2});
        std::vector<int> src = {10, 20, 30, 40};
        v.append_range(src.begin(), 3);
        assert(v.size() == 5);
        fmt::println("After append_range(iterator, count): {}", v.span());
    }
    {
        // Append from initializer list
        fixed_vector<int, 10> v({1, 2});
        v.append_range({3, 4, 5});
        assert(v.size() == 5);
        fmt::println("After append_range(init_list): {}", v.span());
    }
    {
        // Append from range
        fixed_vector<int, 10> v({1, 2});
        std::vector<int> src = {3, 4, 5};
        v.append_range(src);
        assert(v.size() == 5);
        fmt::println("After append_range(range): {}", v.span());
    }
    {
        // Failure case - exceeds capacity
        fixed_vector<int, 10> v({1, 2, 3, 4, 5});
        std::array<int, 10> arr{};
        try {
            v.append_range(std::span<const int>(arr));
            assert(false && "Should have thrown");
        } catch (const std::bad_alloc&) {
            fmt::println("append_range() correctly threw when exceeding capacity");
        }
    }
    fmt::println("");
}

void test_try_append_range()
{
    fmt::println("=== Testing try_append_range() ===");
    {
        // Success case - span
        fixed_vector<int, 10> v({1, 2});
        std::array<int, 3> arr = {3, 4, 5};
        bool success = v.try_append_range(std::span<const int>(arr));
        assert(success);
        assert(v.size() == 5);
        fmt::println("try_append_range(span) success: {}", v.span());
    }
    {
        // Success case - range
        fixed_vector<int, 10> v({1, 2});
        std::vector<int> src = {3, 4, 5};
        bool success = v.try_append_range(src);
        assert(success);
        fmt::println("try_append_range(range) success: {}", v.span());
    }
    {
        // Failure case
        fixed_vector<int, 10> v({1, 2, 3, 4, 5, 6, 7, 8});
        std::vector<int> src = {9, 10, 11, 12};
        bool success = v.try_append_range(src);
        assert(!success);
        assert(v.size() == 8);
        fmt::println("try_append_range() correctly returned false when exceeding capacity");
    }
    fmt::println("");
}

void test_assign_range()
{
    fmt::println("=== Testing assign_range() ===");
    {
        // Assign from span
        fixed_vector<int, 10> v({1, 2, 3});
        std::array<int, 5> arr = {10, 20, 30, 40, 50};
        v.assign_range(std::span<const int>(arr));
        assert(v.size() == 5);
        fmt::println("After assign_range(span): {}", v.span());
    }
    {
        // Assign from iterators
        fixed_vector<int, 10> v({1, 2, 3});
        std::vector<int> src = {100, 200};
        v.assign_range(src.begin(), src.end());
        assert(v.size() == 2);
        fmt::println("After assign_range(iterators): {}", v.span());
    }
    {
        // Assign from initializer list
        fixed_vector<int, 10> v({1, 2, 3});
        v.assign_range({5, 6, 7, 8});
        assert(v.size() == 4);
        fmt::println("After assign_range(init_list): {}", v.span());
    }
    {
        // Assign from range
        fixed_vector<int, 10> v({1, 2, 3});
        std::vector<int> src = {99, 88, 77};
        v.assign_range(src);
        assert(v.size() == 3);
        fmt::println("After assign_range(range): {}", v.span());
    }
    fmt::println("");
}

void test_accessors()
{
    fmt::println("=== Testing Accessors ===");
    {
        fixed_vector<int, 10> v({10, 20, 30, 40, 50});

        // span()
        auto s = v.span();
        assert(s.size() == 5);
        fmt::println("span(): {}", s);

        // operator std::span
        std::span<int> s2 = static_cast<std::span<int>>(v);
        assert(s2.size() == 5);

        // data()
        assert(v.data() != nullptr);
        fmt::println("data()[0]: {}", v.data()[0]);

        // front()
        assert(v.front() == 10);
        fmt::println("front(): {}", v.front());

        v.front()++;
        assert(v.front() == 10+1);
        fmt::println("front(): {}", v.front());

        // back()
        assert(v.back() == 50);
        fmt::println("back(): {}", v.back());

        v.back()++;
        assert(v.back() == 50+1);
        fmt::println("back(): {}", v.back());

        // operator[]
        assert(v[2] == 30);
        fmt::println("operator[2]: {}", v[2]);

        // at()
        assert(v.at(3) == 40);
        fmt::println("at(3): {}", v.at(3));
    }
    {
        // at() out of range
        fixed_vector<int, 10> v({1, 2, 3});
        try {
            [[maybe_unused]] int x = v.at(5);
            assert(false && "Should have thrown");
        } catch (const std::out_of_range&) {
            fmt::println("at() correctly threw out_of_range");
        }
    }
    fmt::println("");
}

void test_iterators()
{
    fmt::println("=== Testing Iterators ===");
    {
        fixed_vector<int, 10> v({1, 2, 3, 4, 5});

        // Forward iteration
        fmt::print("Forward: ");
        for (auto it = v.begin(); it != v.end(); ++it) {
            fmt::print("{} ", *it);
        }
        fmt::println("");

        // Const iteration
        const auto& cv = v;
        fmt::print("Const: ");
        for (auto it = cv.begin(); it != cv.end(); ++it) {
            fmt::print("{} ", *it);
        }
        fmt::println("");

        // cbegin/cend
        fmt::print("cbegin/cend: ");
        for (auto it = v.cbegin(); it != v.cend(); ++it) {
            fmt::print("{} ", *it);
        }
        fmt::println("");

        // Reverse iteration
        fmt::print("Reverse: ");
        for (auto it = v.rbegin(); it != v.rend(); ++it) {
            fmt::print("{} ", *it);
        }
        fmt::println("");

        // crbegin/crend
        fmt::print("crbegin/crend: ");
        for (auto it = v.crbegin(); it != v.crend(); ++it) {
            fmt::print("{} ", *it);
        }
        fmt::println("");

        // Range-based for loop
        fmt::print("Range-based: ");
        for (int x : v) {
            fmt::print("{} ", x);
        }
        fmt::println("");
    }
    fmt::println("");
}

void test_comparison_operators()
{
    fmt::println("=== Testing Comparison Operators ===");
    {
        fixed_vector<int, 10> v1({1, 2, 3});
        fixed_vector<int, 10> v2({1, 2, 3});
        fixed_vector<int, 10> v3({1, 2, 4});
        fixed_vector<int, 10> v4({1, 2});

        // operator==
        assert(v1 == v2);
        assert(!(v1 == v3));
        assert(!(v1 == v4));
        fmt::println("v1 == v2: {}", v1 == v2);
        fmt::println("v1 == v3: {}", v1 == v3);

        // operator!=
        assert(v1 != v3);
        assert(v1 != v4);
        fmt::println("v1 != v3: {}", v1 != v3);

        // operator<=>
        assert(v1 < v3);
        assert(v3 > v1);
        assert(v4 < v1);
        fmt::println("v1 < v3: {}", v1 < v3);
        fmt::println("v3 > v1: {}", v3 > v1);
        fmt::println("v4 < v1: {}", v4 < v1);
    }
    fmt::println("");
}

void test_const_correctness()
{
    fmt::println("=== Testing Const Correctness ===");
    {
        const fixed_vector<int, 10> v({1, 2, 3, 4, 5});

        // Const accessors
        assert(v.size() == 5);
        assert(v.front() == 1);
        assert(v.back() == 5);
        assert(v[2] == 3);
        assert(v.at(3) == 4);

        // Const span
        auto s = v.span();
        assert(s.size() == 5);

        // Const iterators
        fmt::print("Const iteration: ");
        for (auto it = v.begin(); it != v.end(); ++it) {
            fmt::print("{} ", *it);
        }
        fmt::println("");
    }
    fmt::println("");
}

void test_algorithm_compatibility()
{
    fmt::println("=== Testing Algorithm Compatibility ===");
    {
        fixed_vector<int, 10> v({5, 2, 8, 1, 9, 3});

        // std::sort
        std::sort(v.begin(), v.end());
        fmt::println("After sort: {}", v.span());

        // std::find
        auto it = std::find(v.begin(), v.end(), 8);
        assert(it != v.end());
        fmt::println("Found 8 at position: {}", std::distance(v.begin(), it));

        // std::accumulate
        int sum = std::accumulate(v.begin(), v.end(), 0);
        fmt::println("Sum: {}", sum);

        // std::transform
        fixed_vector<int, 10> v2(6);
        std::transform(v.begin(), v.end(), v2.begin(), [](int x) { return x * 2; });
        fmt::println("After transform (*2): {}", v2.span());
    }
    fmt::println("");
}

void test_edge_cases()
{
    fmt::println("=== Testing Edge Cases ===");
    {
        // Empty vector operations
        fixed_vector<int, 10> v;
        assert(v.is_empty());
        assert(v.size() == 0);
        v.clear();  // Should be safe
        v.pop_back();  // Should be safe
        fmt::println("Empty vector operations are safe");
    }
    {
        // Full vector
        fixed_vector<int, 5> v({1, 2, 3, 4, 5});
        assert(v.is_full());
        assert(v.remaining_space() == 0);
        fmt::println("Full vector: {}", v.span());
    }
    {
        // Single element capacity
        fixed_vector<int, 1> v;
        v.push_back(42);
        assert(v.is_full());
        assert(v.size() == 1);
        fmt::println("Single element capacity: {}", v.span());
    }
    fmt::println("");
}

int main()
{
    fmt::println("====================================");
    fmt::println("Fixed Vector Comprehensive Test Suite");
    fmt::println("====================================");
    fmt::println("");

    test_default_constructor();
    test_count_constructor();
    test_count_value_constructor();
    test_span_constructor();
    test_iterator_constructor();
    test_iterator_count_constructor();
    test_initializer_list_constructor();
    test_range_constructor();
    test_copy_constructor();
    test_move_constructor();

    test_copy_assignment();
    test_move_assignment();
    test_initializer_list_assignment();

    test_size_queries();
    test_clear();
    test_resize();
    test_pop_back();
    test_emplace_back();
    test_try_emplace_back();
    test_push_back();
    test_try_push_back();
    test_unchecked_operations();
    test_fill_capacity();
    test_fill_size();
    test_append_range();
    test_try_append_range();
    test_assign_range();

    test_accessors();
    test_iterators();
    test_comparison_operators();
    test_const_correctness();
    test_algorithm_compatibility();
    test_edge_cases();

    fmt::println("====================================");
    fmt::println("All tests passed!");
    fmt::println("====================================");

    return 0;
}

/*

Output:

====================================
Fixed Vector Comprehensive Test Suite
====================================

=== Testing Default Constructor ===
Default constructor: []

=== Testing Count Constructor ===
Count constructor (5): [0, 0, 0, 0, 0]
Count constructor correctly threw for count > capacity

=== Testing Count+Value Constructor ===
Count+value constructor (5, 42): [42, 42, 42, 42, 42]
Count+value constructor correctly threw for count > capacity

=== Testing Span Constructor ===
Span constructor: [1, 2, 3, 4, 5]
Span constructor correctly threw for span > capacity

=== Testing Iterator Constructor ===
Iterator constructor: [10, 20, 30, 40]
Iterator constructor correctly threw for range > capacity

=== Testing Iterator+Count Constructor ===
Iterator+count constructor: [1, 2, 3, 4, 5]
Iterator+count constructor correctly threw for count > capacity

=== Testing Initializer List Constructor ===
Initializer list constructor: [1, 2, 3, 4, 5]
Initializer list constructor correctly threw for list > capacity

=== Testing Range Constructor ===
Range constructor: [100, 200, 300]
Range constructor correctly threw for range > capacity

=== Testing Copy Constructor ===
Original: [1, 2, 3, 4, 5]
Copy: [1, 2, 3, 4, 5]

=== Testing Move Constructor ===
Moved-to: [1, 2, 3, 4, 5]

=== Testing Copy Assignment ===
After copy assignment: [1, 2, 3]

=== Testing Move Assignment ===
After move assignment: [1, 2, 3]

=== Testing Initializer List Assignment ===
After initializer list assignment: [10, 20, 30, 40]

=== Testing Size Queries ===
max_size: 10
capacity: 10
size: 3
remaining_space: 7
is_empty: false
is_full: false
Full vector is_full: true

=== Testing clear() ===
Before clear: [1, 2, 3, 4, 5]
After clear: []

=== Testing resize() ===
Before resize(5): [1, 2, 3]
After resize(5): [1, 2, 3, 0, 0]
Before resize(3): [1, 2, 3, 4, 5]
After resize(3): [1, 2, 3]
Before resize(5, 99): [1, 2]
After resize(5, 99): [1, 2, 99, 99, 99]
resize() correctly threw for count > capacity

=== Testing pop_back() ===
Before pop_back: [1, 2, 3, 4, 5]
After pop_back: [1, 2, 3, 4]
pop_back on empty vector is safe

=== Testing emplace_back() ===
After emplace_back: [10, 20, 30]
emplace_back() correctly threw when full

=== Testing try_emplace_back() ===
try_emplace_back success: [100]
try_emplace_back correctly returned false when full

=== Testing push_back() ===
After push_back: [5, 10, 15]
push_back() correctly threw when full

=== Testing try_push_back() ===
try_push_back success: [5, 10]
try_push_back correctly returned false when full

=== Testing unchecked operations ===
After unchecked operations: [1, 2, 3, 4]

=== Testing fill_capacity() ===
After fill_capacity(7): [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]

=== Testing fill_size() ===
After fill_size(99): [99, 99, 99, 99, 99]

=== Testing append_range() ===
After append_range(span): [1, 2, 3, 4, 5, 6]
After append_range(iterators): [1, 2, 3, 4, 5]
After append_range(iterator, count): [1, 2, 10, 20, 30]
After append_range(init_list): [1, 2, 3, 4, 5]
After append_range(range): [1, 2, 3, 4, 5]
append_range() correctly threw when exceeding capacity

=== Testing try_append_range() ===
try_append_range(span) success: [1, 2, 3, 4, 5]
try_append_range(range) success: [1, 2, 3, 4, 5]
try_append_range() correctly returned false when exceeding capacity

=== Testing assign_range() ===
After assign_range(span): [10, 20, 30, 40, 50]
After assign_range(iterators): [100, 200]
After assign_range(init_list): [5, 6, 7, 8]
After assign_range(range): [99, 88, 77]

=== Testing Accessors ===
span(): [10, 20, 30, 40, 50]
data()[0]: 10
front(): 10
front(): 11
back(): 50
back(): 51
operator[2]: 30
at(3): 40
at() correctly threw out_of_range

=== Testing Iterators ===
Forward: 1 2 3 4 5
Const: 1 2 3 4 5
cbegin/cend: 1 2 3 4 5
Reverse: 5 4 3 2 1
crbegin/crend: 5 4 3 2 1
Range-based: 1 2 3 4 5

=== Testing Comparison Operators ===
v1 == v2: true
v1 == v3: false
v1 != v3: true
v1 < v3: true
v3 > v1: true
v4 < v1: true

=== Testing Const Correctness ===
Const iteration: 1 2 3 4 5

=== Testing Algorithm Compatibility ===
After sort: [1, 2, 3, 5, 8, 9]
Found 8 at position: 4
Sum: 28
After transform (*2): [2, 4, 6, 10, 16, 18]

=== Testing Edge Cases ===
Empty vector operations are safe
Full vector: [1, 2, 3, 4, 5]
Single element capacity: [42]

====================================
All tests passed!
====================================

*/
